global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wellconnect_app'
    static_configs:
      - targets: ['app:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb:9216']
