global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'wellconnect_pro'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'system_health'
    metrics_path: '/api/health'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
